//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
    
        public virtual Members Members { get; set; }
    }
}
